apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tavily-mcp.fullname" . }}
  labels:
    {{- include "tavily-mcp.labels" . | nindent 4 }}
data:
  MCP_PORT: {{ .Values.config.mcpPort | quote }}
