helm:
  parameters:
  - name: image.repository
    value: europe-west1-docker.pkg.dev/stellantis-490509/brain-mcp-tavily/tavily-mcp
    forcestring: true
  - name: image.tag
    value: latest@sha256:cbf76906519b785d513b1882e5d76c476d8a614a990017c8c16c2ad2d670272a
    forcestring: true
