helm:
  parameters:
  - name: image.repository
    value: europe-west1-docker.pkg.dev/brain-staging-450115/brain-mcp-tavily/tavily-mcp
    forcestring: true
  - name: image.tag
    value: latest@sha256:95c22dad79c78822aae103d2fd9124cd1ea933802b0a69f10dae1bf8702744d3
    forcestring: true
