helm:
  parameters:
  - name: image.repository
    value: europe-west1-docker.pkg.dev/brain-staging-450115/brain-mcp-tavily/tavily-mcp
    forcestring: true
  - name: image.tag
    value: latest@sha256:cc7e8aaea6b434bc61428d569b3c2c15391bf4fbc5fd59b94dc23b4df6217a90
    forcestring: true
