replicaCount: ENC[AES256_GCM,data:iQ==,iv:z1wjF1oV1OH8ONL0n+0rCMowKdLfooWMuPDK0bvPMgE=,tag:/Z7kQh0TdGLLHQQYbttKAQ==,type:int]
image:
    repository: ENC[AES256_GCM,data:s23pl2uvlC6cHHe74Amo/eqvrSsygI5lvBnod6FidMi7Hi1mu6SvD3okKcMCC1nBqJmpKIzQrxl3wDlH0aSXy8FgqEmNK0iCLA==,iv:ww6IViNJrsdBFjd4tY+2sCjvvmjmPpPC5w7FgKsfUqM=,tag:Ks0bKp6FE92DLK5pnP5WqQ==,type:str]
    tag: ENC[AES256_GCM,data:i+aOW/m1,iv:Y0/gAceDif5wRrC8ooTN0luUuapPfIdHYPXbVNn4bTw=,tag:9b6QaYiNNQ07r/9hz1IAFA==,type:str]
    pullPolicy: ENC[AES256_GCM,data:uTZ2CUd4Y13i+r8r,iv:8TEaGMdIlC87YATXnEnQnFcL4tS7TDayaCKVjryKNLM=,tag:CAF8k2e4kXQLL2JKH7/YqA==,type:str]
#ENC[AES256_GCM,data:4XrpGl8bCPe8W6I8CJ4QZzC0VkLfTYc9/SpI,iv:dP4Sm7vjlG0enhtvtf9Za1UIQQNbe+sJDOpkpg6bp/8=,tag:58E9/QM90KmzNoGdfM/5og==,type:comment]
#ENC[AES256_GCM,data:XdOkNYdINCHaMlHm2TcdQMtUDpT4FGH94vBLPOFYUWtKz1fR3lXhRHQJY/reNrwmtbIq8pBw85qbBFn8Sq/viLzuOU46QBYchDdCCxJbqdImwio=,iv:Qy0uewFvp72lYhABTMYJlp0QKgKa4d9GyRSnIdSauvs=,tag:9Cq+8FjWt4lDWrJ/DWyL4w==,type:comment]
secret:
    tavilyApiKey: ENC[AES256_GCM,data:J7STA7mSmFIZaLvZpTVOJYHRKxOVlyPe/wekBrlXmfqMVNcaEmmeWIfJh+q8WdO7fOdXLlu+MSa5fw==,iv:SVX6VhHwAU+NAPNYzgiBMtoqfvmpAS3SnuIQfVZtiBs=,tag:XE4i/vXbAY+k+N+XSfIDQA==,type:str]
    existingSecret: ""
config:
    mcpPort: ENC[AES256_GCM,data:Kn0Z4g==,iv:Mpisy+gxqL8sD/i15/K4gKgJELh70n1N87NtoLZjPLQ=,tag:1yMRVYGgqvnpATvE+SPBSg==,type:str]
service:
    type: ENC[AES256_GCM,data:Yf+zctq/UHpd,iv:A9gF9aKpsX+IRwHaytwpoH+wi3QKbKO1us8NvJRp2yQ=,tag:Ocjapx239bkYGFmQvyPrxg==,type:str]
    port: ENC[AES256_GCM,data:CuRjuQ==,iv:ThMGRhG1LJVNLOPZMDLhHpGHn9MLTBxbebKY/zXyaH8=,tag:Yl3o6ei/vfgtNnq/Aezq/Q==,type:int]
resources:
    requests:
        cpu: ENC[AES256_GCM,data:JW46Fg==,iv:7+dl9HcqzXkY9s8wlSNThf0XCrtq6vJS+UE3ed6A0RU=,tag:F3h5NZTnNRqP/tjdC9s8oA==,type:str]
        memory: ENC[AES256_GCM,data:AFE31WU=,iv:onJM0O8St3NJbcwYddzLHHJTaPXwt3dzCpxpR1KyJRk=,tag:LoiPx8dZApf3ggbYdiuMpg==,type:str]
    limits:
        cpu: ENC[AES256_GCM,data:dQ==,iv:YCSJ7L4VVPOQj5NKGi1DirEnFA7CBWzf+h8zMg0+S6M=,tag:xYayhUx5irmS0/qkETNrFA==,type:str]
        memory: ENC[AES256_GCM,data:k7gJ,iv:++LaBspMawuuS79Uza7dApWPTWvItW+vSoXyRK7UEQQ=,tag:os3ga5Lu/AWxcP7HzpX0dg==,type:str]
autoscaling:
    enabled: ENC[AES256_GCM,data:HimIv90=,iv:mUkeEVPVbgLrlKKbvOF+1jLRY242Qf7t+rbL7nbO5GU=,tag:aA0vkqcHOsLiyhfBCjOPhA==,type:bool]
    minReplicas: ENC[AES256_GCM,data:4A==,iv:FNwhwzQUxNYxCWXEzpQcf3mLjhC7EtbDwAySONd0PFc=,tag:E8bLgeY3lkxbkzjBz/xSlA==,type:int]
    maxReplicas: ENC[AES256_GCM,data:DQ==,iv:SDJZGcUwnnVej2lRgwU1L3D1wOKMZ6q6e53pnu5B9tE=,tag:jxxxCtbcrSWTTZ6Prv/kLQ==,type:int]
    targetCPUUtilizationPercentage: ENC[AES256_GCM,data:Pug=,iv:EkxxsjCEa4hzXQX9aeMUtrnIPxyrAJh9P9j4GG2Hnyg=,tag:M+A7LjHo5e3M2JPI3BpoTQ==,type:int]
probes:
    liveness:
        initialDelaySeconds: ENC[AES256_GCM,data:fLM=,iv:MfLpENQkbepy01+hzntVDuYSTKSuXuY4Jfq6VswOLuA=,tag:5Xm1M6wRVuzYSkP6R7mCow==,type:int]
        periodSeconds: ENC[AES256_GCM,data:Fh8=,iv:ovrSUzcEZV6cOm9eqX9V5/X484s35HbHKF9xCPw9vkc=,tag:SguuV5zdTml/UIgfLodSnw==,type:int]
        timeoutSeconds: ENC[AES256_GCM,data:vQ==,iv:vh/4Ku6Be7CG8RMXCS/cmXRWcfeg34mWjadSxGVXwbU=,tag:5rgXvUx6TfQ5aDGg6Qeyyg==,type:int]
        failureThreshold: ENC[AES256_GCM,data:dg==,iv:YVGPK9UrcDbn27dOCKm8gRpUjqB8IGqCJ6ZIJnWiXHw=,tag:4M6khPj9IHskMNYRr/b4nA==,type:int]
    readiness:
        initialDelaySeconds: ENC[AES256_GCM,data:+A==,iv:gKDP/W0YZ/dFYL6Nt0nePO/Tri8EjXUy7ZawOe/gr0Y=,tag:Z0VJQhIeOZVgRGEzLJH/9w==,type:int]
        periodSeconds: ENC[AES256_GCM,data:BKc=,iv:KPAnUr6wl1zRImJqiZKwMxD6UHoZF5O48Cm4xJbnsag=,tag:olYUS/9fifjRzYpNjyH7SQ==,type:int]
        timeoutSeconds: ENC[AES256_GCM,data:FQ==,iv:qnAlfF6d5e6TwFNwc5Pqienzdr8OvvwTKA/Zwt8xBV4=,tag:/BMNAZuNCyczeoTZ5oIs4A==,type:int]
        failureThreshold: ENC[AES256_GCM,data:3Q==,iv:VD3vHWAGomC3+xHXwQKuIA03anOBxEHxjp1vGtU00HU=,tag:I8YuJmXeuCnvjNOv+p29Vg==,type:int]
nodeSelector: {}
tolerations: []
affinity: {}
sops:
    lastmodified: "2026-06-02T13:49:15Z"
    mac: ENC[AES256_GCM,data:rf1I+0HjnRuXg1oGvLAOMIN8TmJAPOCwKCzBv5Ysazlp2CU1Jj15aWI4nznirMLFyTF00Pnn+2GWR/gEnislaiPn6IkdoDnAXkm9vShJ4fSmi4fBo+xiC1i1hZF13KSanYfszoX9IDWbfDTM6Wzl87fuUs4lOE3maQ8GztV3ls0=,iv:3PYBR6ZOft8183UawnWywrSPZEI2Oq5476gtLTeVUOQ=,tag:2N70soQSXQonOuta9W8+XQ==,type:str]
    pgp:
        - created_at: "2026-06-02T13:49:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA9vn3oG2RG7UAQ/+M8CO6AUMsipUTjomportJZNt+s0H2RHyt4iNPfs/mRPg
            QQ1ulrt96JFWihr6Rj/UvNDqeB39RFvHyfVMaQwm0rjmdkA/RreojYFcHkJDiyiC
            hyGgnISqc1bVm1Yyp1/GZq4rY/gr/k1HhtYZqpSyhI0+8460ouA82PZqyk+NElwQ
            tDvo8lxQp0f885qWcdB0nzTjVkeRv0cUj5Hkgc5cUhLMaHnsqFebnt3OOL/hiZzi
            emF8VZCbSGnyexc/lwYwS2BdC/4elnhI91cXIkW/H1YSfZeW5N1oC+LxyjC8G1DI
            hiR8inm3Z30YmV1G2h2ZjZWMCL0YUzQeWvEfEfP8eaIOT0TtQtNYGA7aYjJBVbqj
            vrmDIhS7qxf4Af33doHwl+uq8aS2w3K0t654NuNyyoGr5S6xo0BP3RJQy2N0iyhQ
            o+bXzS3+tkV6qabUsGsUaht4HdNtww1GqgCh1a+HOpSw3e3kiXFLZRDaAHLpNQ3/
            G6VCIVne6cVQAYO335gjDHzG+6i/vXg1GGKTAjH/fQmY+zlpGL2WrX8WHwUqkTTE
            UftYQ3GSY/HHScDdKlp/BkicpAURHb+elHsfaSjery6sqaJBjKj6O66tI374vhLx
            7pJzQDfY59nspjbCxdQDYnIWT/T6l7rzV97vrQIfyA+0FZIKkDByJlmDlKhdeo3S
            XgHP6B7YGR5mL+K8yWTAp579AkpeFLrVTm5028F1EMcu1pw308RhkiP6vpmUXCVr
            mxCDRk/QDqENg3E873603/NYCo58jQCyY0O442qFByuO73K5DtIJYZBThBrtROU=
            =NMS1
            -----END PGP MESSAGE-----
          fp: 1B1C3D5E284D1E6C0105E42359159BBF6E4AB5DB
    unencrypted_suffix: _unencrypted
    version: 3.12.1
