replicaCount: ENC[AES256_GCM,data:hg==,iv:/ZlQSXdXNcjCDKtbL9Hbqcl2Kj1Wf+Sk0o3lU1OaMkk=,tag:/t1Vk7YOfxTlB7KvA7HoYQ==,type:int]
image:
    repository: ENC[AES256_GCM,data:dadN+xWqOlu/OD6h0Ea8jl9fugpbPbD4awVQ6AcnrkLo160s0a0cR25n9x+iwdK5oyavdCJhU0QHY5+1ywclJxDcm3diW0LyWg==,iv:PeqeczwE7eZhBhjqirQKscG9BOBIHDveNsi8SqG5k1Y=,tag:K3HvFEHc8QGrt0g/zTrbsw==,type:str]
    tag: ENC[AES256_GCM,data:TES5pWO4,iv:XoGYrunwfr+BGzdUWvUNe0v3rF9WXyl1lOw5Zj2uZ0c=,tag:hnbnhtOL1ZwFSS5ZOnSnJg==,type:str]
    pullPolicy: ENC[AES256_GCM,data:w61pivDrJLLYszB7,iv:5J6rvCME84n+dEw4ECbDMK6f0J6BVsilSzhTCJA4KyE=,tag:uGOPJ88ToqkIlUvFur3z9A==,type:str]
#ENC[AES256_GCM,data:dYRoxZyKhYeH0bVv+CSmU+jdwoz+pvdcNqGX,iv:OHitB/vGWGTadSLoZQZvItPmQMcnbwSwFZW2lUcOjtE=,tag:JafvSMfBO29F9yuRrCaBQQ==,type:comment]
#ENC[AES256_GCM,data:rxgVKTYwMZwbhYF738E14oTcnIVRyw/4OYdtQMvVxJD1EIcxnMhHhxzDVq3u0Eve2rW06Yjm8qUcn43G4snHqHp9VTHu6SqbyZxrWsa4oYWC2G8=,iv:EXFGa+oYCiw+4LK4LZcGpjFH8wB+wk04UxziCNwz51s=,tag:TgruAoqM4pr72CmFCbBjVA==,type:comment]
secret:
    tavilyApiKey: ENC[AES256_GCM,data:vQ230aBBPnc2RuMwCTpmF4kd0rmqoBcL0h4LpcsaaP+EX2JYOsmXfqsDhrf3IuRoDvJ0Nw6It4iZ9w==,iv:OgrZ30WR8OngEOHvkwf1iKIBu74NjXxAm1SpMbx8Knw=,tag:LowpwAL/2exl86s0akd4dQ==,type:str]
    existingSecret: ""
config:
    mcpPort: ENC[AES256_GCM,data:ITjdnA==,iv:9KOd9YNSEDrsfsxsOM6AMiwNiHXj5A6HW+3tHpu3cLQ=,tag:nzyJvUvI8qBma439aWin+w==,type:str]
service:
    type: ENC[AES256_GCM,data:YmSD9AcJQl2M,iv:OsBE/SbQt8L5quAmjgHItJdForTcqfRQ2P8T1dDDLIk=,tag:2GK/DZNS5J4DP3dQSkBd1Q==,type:str]
    port: ENC[AES256_GCM,data:Env6cQ==,iv:uQe6/DN57Skzrh8SZfuqx7semQAKQWqXCFRpJ+q4r8w=,tag:CTVn4r56bikvpsFHaGtNKA==,type:int]
resources:
    requests:
        cpu: ENC[AES256_GCM,data:g+j5Rw==,iv:OT0sXJVYf5BzDsxVGZURqvW41j0vfioIb6zm+woBK20=,tag:Z59bKYFSo2jh38ph1TPZWg==,type:str]
        memory: ENC[AES256_GCM,data:l88kvQI=,iv:cKpxbTRKAoeRaZI+cyQZ7aF37E7g2z1ghOqJZBwXLkI=,tag:8fJG7OUPX7zz8YnatMjcsA==,type:str]
    limits:
        cpu: ENC[AES256_GCM,data:elFekA==,iv:EfZGVqjgcRXX5YtKkr58CLADOLAnCjOE0UeYggQa61c=,tag:H3d/WufGys7wiBWmMNZHYg==,type:str]
        memory: ENC[AES256_GCM,data:UYqe5rg=,iv:qqzltGTL4BajaKlIUfGK4tblhpsFeVyS+GVvi+T029E=,tag:xT567rqMs6d7Tiqs8T3gRA==,type:str]
autoscaling:
    enabled: ENC[AES256_GCM,data:h8VyzpQ=,iv:OsHS9sjkvgrDW29J9+nEbKCcGRpeJhN8+5fY+z8ZsPc=,tag:JQWeD0cHzodOlOz/G7JVOg==,type:bool]
    minReplicas: ENC[AES256_GCM,data:Vw==,iv:3ONZgcaiSwbmcHJL9xTIOaC/ngfakuOBaUdGseCWHG0=,tag:/ULRgBrrfnubuHMbnA1x/A==,type:int]
    maxReplicas: ENC[AES256_GCM,data:MQ==,iv:3Q8QTdS99PrusXXkfwaRAlKeAhHw2KFctGVS29bntMI=,tag:72ATujW/KrsWtsHZ1soiOA==,type:int]
    targetCPUUtilizationPercentage: ENC[AES256_GCM,data:C1g=,iv:xCNHohMzQYzxm7eQFvtSNiWkD3+8qm+/DeG5lW7wdh0=,tag:H2IQ/yw+HnLiERJoMJLffw==,type:int]
probes:
    liveness:
        initialDelaySeconds: ENC[AES256_GCM,data:Eqk=,iv:gzp85mzVlB5ex66gX2CjEZqdeZAzlBEATxJzwQL0sMQ=,tag:/zaJ1xvlD42cgG3OozwIcg==,type:int]
        periodSeconds: ENC[AES256_GCM,data:vic=,iv:D7z9xQ3dHbwKULTqk/CoTkCll64PUp04JRrT8gJGT+s=,tag:I8QZ6QzTSxMiSEaLfaUeXQ==,type:int]
        timeoutSeconds: ENC[AES256_GCM,data:EQ==,iv:leyhk1X0qMtQKT99yr6VlZMdWH1Kq1KWfm/PCzEi1Ck=,tag:aGBPir6l3CQDbHKvgk3LNA==,type:int]
        failureThreshold: ENC[AES256_GCM,data:DA==,iv:diLrWQopyfrk3UbjpUgPtULSrWCHpertgDQ5vHNPYSI=,tag:/nADcApzQuuizX/DfQM+gA==,type:int]
    readiness:
        initialDelaySeconds: ENC[AES256_GCM,data:8Q==,iv:272+V7ulAYHqKGtB49Nli5lhzGL5YC+xsNnRcVSWxeA=,tag:nJ/fUcxFSkcGTbsrz6vzhA==,type:int]
        periodSeconds: ENC[AES256_GCM,data:hfg=,iv:UhixAT+F2Hgf27KqzOvBGodM0OwcFKfAcFXGiuMPi8M=,tag:0/Q5Mp4FyzMx8d/O81jrHg==,type:int]
        timeoutSeconds: ENC[AES256_GCM,data:LQ==,iv:lLaTAtfUhxcOYkHip2TnN2kiHPevrxmPfV7O1TXY1Dg=,tag:+SHlfokR7eyMJNXWnlCY7g==,type:int]
        failureThreshold: ENC[AES256_GCM,data:Rw==,iv:q3uh1kg2eayDlpmNjTTLtLbeBqe123WpLq6mCRYFBfM=,tag:jSehG4i99KqjdEASB5yH7Q==,type:int]
nodeSelector: {}
tolerations: []
affinity: {}
sops:
    lastmodified: "2026-05-20T16:02:14Z"
    mac: ENC[AES256_GCM,data:3OlQVR2R4Ta6jZl7B4gIXylhSinGl+EmKWdM7EczPucV0uR5CYumX9uz2IniYkuj86qykw8TAbjtZO6Dz0/Ldp5KCbqqtMOmH/YpACvRkJOOxsLGIBqxR8dfR4ECuAs2NHRDkeGGmnXCWhO3QGoAALIoZqTKbYgIopcMu9yH/Bs=,iv:TRn8icNJbZy6I4VziSfU1jPiAUniktpe2epFSfhxjVs=,tag:+CK/M+i1SnEE4IR7Dk20rg==,type:str]
    pgp:
        - created_at: "2026-05-20T16:02:14Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQIMA9vn3oG2RG7UAQ/+NWO18rPtRwEpbcufaokTl7NhEz3te8FVtBUv9TqiuSWE\r\nhlEs8X3Dwz4bmW3EfMStrTfO9Jip9x2mrMaoJHySijBDujKkxGfgC3L+Bkw1spCP\r\nKOuVD/Zh5/OIScCVfpoIv9KROUH5EWdcorw9R9q4mMLOAsT3hbCK5CSePvMymyWB\r\ndW8qdgFGOBt0TeMI7JjsO3oZSnpqA6dIsHkeLGuWS+c5qV2ybuJh6mDAaYYUEJ5H\r\nGqmWWdRUxYUdIrmkZEpamSyH7ttoBcu4MFz6UNHBKAaJe3DzT+ZkC/ejMSaAss73\r\ndYTJd44VnJhv9CnMqE0HvnKfWQW+cOXCTRU99VIBw1TM6AzFtYoZB1uX6MlCAo+k\r\n1+P1/2C/wv7Avc3eFNNyEB1weThFfKtmGaMg8ER2m9Fz32+H6kRDqEJTwm+BXioz\r\nwDdcrrZQZhftTPpLjwME4T5AebYPgZjs0jV4Rc2opR4OTqS3MuO81779IaRKA6DZ\r\nnywXpV6tlLwyeRugJwSkSxTVTKC9B+EO0zcO6PcVzQjnkSpYBN5kju5P3F0+rBmI\r\n7oWTRjlYocQQDbr+Uc4ScKhrlVWFAAtUrDrGcuZnBAAAMwZYcs9ltX9eAWOMPKiz\r\n/XNpT6rlQ7g3jbZp8USIOLQlRcpoLGiX5HpDYE9tW2pSBnwf9uO8SzxAqvV6j4PS\r\nXgGUGfa5FqyWz+oEx18osVhniQQbVsiA/eHCWe4NaGTXINOulrt6+WlB+NcowWq/\r\nuxTQ+UB/bOwgg/7rwV27cl96dFar0JaZhx/qxJxJUuZhW4xYWSLZEmRO3P+UiHY=\r\n=tkWf\r\n-----END PGP MESSAGE-----"
          fp: 1B1C3D5E284D1E6C0105E42359159BBF6E4AB5DB
    unencrypted_suffix: _unencrypted
    version: 3.12.2
